DFE-Digital/github-actions

- GenerateReleaseFromSHA/README.md
- GenerateReleaseFromSHA/action.yml
Initial cut of PR-INFO. 
When passed in the commit SHA of the current run, if it belongs to the merge_commit_sha of a PR then grab that data from the PR.
> Pull Request Info

- DraftReleaseByTag/README.md
- DraftReleaseByTag/action.yml
We need to publish more information to the slack channel in our workflows.
Since we are already addressing the release is this call, it would not take much effort and very little processing to make some of the details available so we can consume
> Improve Outputs of Release Details

- DraftReleaseByTag/action.yml
The jq command needs raw output on body and name
> Removed quotes from body and name

- .github/env.yml
- .github/workflows/test-setup-environment-variables.yml
- set-up-environment/README.md
- set-up-environment/action.yml
Action to set environment variables from a yaml file.
Co-authored-by: Vignesh.N <vigneshmsft@users.noreply.github.com>
Co-authored-by: Steve Fawcett <sfawcett123@users.noreply.github.com>
> Setup environment variables action

- CopyPRtoRelease/README.md
- CopyPRtoRelease/action.yml
Create the new Action "Copy PR to Release" 
This action will extract the body of the PR and push it to the body of the release, attempting to keep formatting.
> CopyPRtoRelease added

- DraftReleaseByTag/action.yml
Multi-line bodies are only displaying the first line 
It seems that bash just cannot handle the process. So converted to powershell and it worked straight off/
https://github.com/sfawcett123/Test/actions?query=workflow%3A%22Update+Release%22
> Convert to Powershell

- .github/workflows/test-validate-key-vault-secrets.yml
- validate-key-vault-secrets/README.md
- validate-key-vault-secrets/action.yml
Common action to check if secrets stored in Azure Key Vault are valid YAML
> Action to check if secrets are valid YAML

- SendToLogit/README.md
- SendToLogit/action.yml
Added a new action to push JSON to logit.io
> Added Action to Push log messages to Logit.io

- AddTrelloComment/README.md
Add an example of how it can be used in a PR workflow
> Improve Trello Comment ReadMe

- keyvault-yaml-secret/README.md
- keyvault-yaml-secret/action.yml
Extracts a single secret value from a YAML file stored in Azure key vault
- Follow README
- See successful run: https://github.com/DFE-Digital/register-trainee-teachers/runs/3914822649?check_suite_focus=true
> YAML secret

- README.md
Adding a link to the source code from the README so it makes sense on github_pages
> Adding Source Directory to Readme

- CheckServicePrincipal/README.md
Add a line to the README to explain the required permissions
> Document Access Requirement for SP

- README.md
Updates the readme with some links and a new description. Hopefully this content can grow and in the future reference some best practice articles in the tech docs.
> Give the readme some sparkle

- CheckServicePrincipal/README.md
- CheckServicePrincipal/action.yml
The workflow is useful, but needs some refinement before rolling out to BAT. We should tidy the logic and output and always return useful information and a proper alert status.
Before merging:
> Improve the workflow for future uses

- build-docker-image/README.md
- build-docker-image/action.yml
Build the docker image, with or without cache and push to the Github container registry.
Use as described in the README
Successful run: https://github.com/DFE-Digital/teacher-pay-calculator/actions/runs/5415001504/jobs/9843025806
> [448] Build docker image action

- build-docker-image/README.md
- build-docker-image/action.yml
This is a full reference to the image directly suitable for us by Kubernetes.
> Add image output to build docker image action

- build-docker-image/action.yml
It should be `description` rather than `describe`.
> Fix incorrect key in job output

- set-kubelogin-environment/action.yaml
Fix bug:
```
Error: Unable to resolve action `DFE-Digital/github-actions@925-rbac-migrate-clusters-development`, unable to find version `925-rbac-migrate-clusters-development`
```
Point at master
Test calling the action
> [925] Bugfix: point kubelogin at set-arm-environment-variables master

- README.md
- set-kubectl/README.md
- set-kubectl/action.yaml
Added kubectl   action  
Added kubctl  acrion can be refered by all pipelines
Test Pipeline : https://github.com/DFE-Digital/publish-teacher-training/actions/runs/9091604641
> Added kubctl github action

- set-kubelogin-environment/action.yaml
Kubelogin version upgraded to v0.1.3
Kubelogin version upgraded to v0.1.3
Testing is done  this  branch : https://github.com/DFE-Digital/check-childrens-barred-list/actions/runs/9301027313/job/25598360782
> Kubelogin version upgraded to v0.1.3

- backup-postgres/README.md
- backup-postgres/action.yml
Create a reusable action to backup a postgres database
Add backup-postgres action
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/9644386638
> Create backup postgres github action

- backup-postgres/README.md
- backup-postgres/action.yml
- restore-postgres-backup/README.md
- restore-postgres-backup/action.yml
Create a reusable action to restore a postgres database from a previous backup
Add restore-postgres-backup action
see test run (tba)
> Restore postgres from backup github action

- set-kubectl/action.yaml
Kubectl version upgraded to 1.28.9
Kubectl version upgraded to 1.28.9
> Kubectl version upgraded to 1.28.9

- backup-postgres/action.yml
- restore-postgres-backup/action.yml
Set konduit.sh to use a separate deployment.
This removes any requirement or impact on the web app.
Update backup and restore postgres actions to use konduit with the -x flag
backup test run https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/10061528497
> Update konduit to use separate deployment

- ptr-postgres/README.md
- ptr-postgres/action.yml
Add github action to perform a point in time restore of an existing Azure Postgres flexible database server.
https://trello.com/c/OB8Hvgii/1856-dr-postgres-point-in-time-restore-github-action
Create action ptr-postgres
see https://github.com/DFE-Digital/register-trainee-teachers/pull/4493 and https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/10076780745
remove dev6 option
> Add postgres point in time restore action

- .github/dependabot.yml
Add DevOps label to align with maintenance processes.
> Dependabot.yml labels

- backup-postgres/README.md
- backup-postgres/action.yml
- maintenance/README.md
- maintenance/action.yml
- ptr-postgres/action.yml
- restore-postgres-backup/action.yml
Moving more of the DR template workflows into the related github actions
- additions to backup and restore workflows
- add maintenance action
Run against this branch from ittms staging 
- backup: https://github.com/DFE-Digital/itt-mentor-services/actions/runs/11328445134
- ptr: https://github.com/DFE-Digital/itt-mentor-services/actions/runs/11328145369
- ptr backup: https://github.com/DFE-Digital/itt-mentor-services/actions/runs/11328519109
- restore from backup: https://github.com/DFE-Digital/itt-mentor-services/actions/runs/11350529580 (restore cmd replaced with a select stmt)
Existing services that use these actions will need to be updated at the same time
i.e. ittms, trs, claim (and check for any others)
> Update actions used by DR template workflows

- maintenance/action.yml
error in maintenance action, incorrect input specified
rename to correct input
check change looks right
> fix input error in maintenance action

- maintenance/action.yml
error in maintenance action, syntax error
correct syntax
check change looks right
> fix syntax error in maintenance action

- maintenance/README.md
- maintenance/action.yml
https://github.com/DFE-Digital/npq-registration/actions/runs/11738475177/job/32701068931
Use the make ci target to skip the confirmation
Code review. It will be tested in production in ECF soon.
> [2135] Maintenance: skip CONFIRM_PRODUCTION

- delete-review-app/README.md
- delete-review-app/action.yml
We want to be able to delete a review environment and delete all versions of the terraform state file 
this action is callable to delete a review environment and delete all versions of the terraform state file
see also https://github.com/DFE-Digital/teacher-services-cloud/pull/312
see https://github.com/DFE-Digital/teacher-services-cloud/pull/312 for testing of this PR. 
Trello Card [delete review app workflow template](https://trello.com/c/IqDW5aC8/2092-delete-review-app-workflow-template)
> Delete review app action

- set-kubectl/action.yaml
https://trello.com/c/UAxI1HVZ
There is a requirement to keep up with the Kubernetes releases for bug fixes and new functionality. 
Update the kubectl client version to match the aks cluster version 1.30.6.
kubectl client in github actions should use the updated vesion.
> Update kubectl client version to 1.30.6

- deploy-domains-env/action.yml
Actions for CI-CD for domains 
ariable name for output of CI-CD domains
tested by using the itt-mentor-services to run workflows to call these actions.
> Improved variable name for output of CI-CD domains

- backup-postgres/action.yml
- restore-postgres-backup/action.yml
Identified potential issues when running DB workflows
- Fetch konduit.sh from the main branch instead of master
- Use the $AAD_LOGIN_METHOD variable for kubelogin
Successful run: https://github.com/DFE-Digital/apply-for-teacher-training/actions/runs/13265759718/job/37032694331
> [2201] DB action fixes

- README.md
- delete-review-app/README.md
- delete-review-app/action.yml
added terraform file var for tenants whose tf state version is not located in expected terraform.tf file
add new input var - "tf-file"
> feat(2323-use-delete-review-app-github-action): add variable for tf-file

- restore-deleted-postgres/README.md
- restore-deleted-postgres/action.yml
Adding the actions for the recover deleted postgres workflow
Adding the actions for the recover deleted postgres workflow
This is tested in ATT.
https://github.com/DFE-Digital/apply-for-teacher-training/actions/runs/16145498440
Deleted and recovered postgres
s189t01-att-qa-psql-ptr-test
Deleted activity in Azure monitor
https://portal.azure.com/?feature.msaljs=true#view/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/~/activityLog
Filter test subscription & resource group s189t01-att-qa-rg
Identify the deleted resource
Delete PostgreSQL server
It should be /subscriptions/20da9d12-7ee1-42bb-b969-3fe9112964a7/resourcegroups/s189t01-att-qa-rg/providers/Microsoft.DBforPostgreSQL/flexibleServers/s189t01-att-qa-psql-ptr-test
deleted time
2025-07-08T13:46:17Z
recreated postgres …
> Adding the actions for the recover deleted postgres workflow

- build-docker-image/README.md
- build-docker-image/action.yml
Updates to the build-docker-image action. Allow services to
- override build tags and cache settings
- set a different main branch 
- customise the Dockerfile sha
Updates to the action 
service deploys run against this branch (no changes, just pointing to this branch, and they should run as before)
https://github.com/DFE-Digital/teacher-pay-calculator/actions/runs/16070876522
https://github.com/DFE-Digital/apply-for-teacher-training/actions/runs/16194776139 
https://github.com/DFE-Digital/apply-for-teacher-training/actions/runs/16196174922 
https://github.com/DFE-Digital/register-early-career-teachers-public/actions/runs/16196412017 
https://github.com/DFE-Digital/register-early-career-teachers-public/actions/runs/16196619664 
service with changes to use the new features (customised tag …
> Build docker image override tags
