DFE-Digital/github-actions

- DraftReleaseByTag/README.md
- DraftReleaseByTag/action.yml
There is no method to get draft releases, so by using this code we can
create a draft release earlier in the pipeline and when we are ready we
can convert it to a published release.
This code is used to find the draft release using the API. You need to
pass in a GITHUB_TOKEN with access to the repository because draft
releases are usually kept private.
> Draft Release By Tag

- DraftReleaseByTag/README.md
- DraftReleaseByTag/action.yml
This change will add the target-commit-sha to the output of the release query.
Thus making it useful in Manual releases, and remove duplicate code
> Add target-commit-sha

- install-postgres-client/README.md
- install-postgres-client/action.yml
- setup-cf-cli/README.md
- setup-cf-cli/action.yml
Per TEVA-1937, created custom actions to allow re-usable:
- installation of CloudFoundry CLI
- installation of Postgres client
Both allow specifying a version. CF CLI allows specifying a release.
To be merged before TEVA-1414, which uses the custom actions
Successful run shown against a temp commit, invoking the actions from a branch, and targeting the `teaching-vacancies-review` space: https://github.com/DFE-Digital/teaching-vacancies/runs/1786168712?check_suite_focus=true
> Create CF CLI and Postgres client actions

- CopyPRtoRelease/README.md
- CopyPRtoRelease/action.yml
When a PR is created by Snyk or Dependabot quite a lot of text is provided, that our community are not interested in and it floods our slack channels. They are happy to see the title of the PR instead.
This change allows a list of users to be passed in, which if the PR is created by one of those users the title is chosen rather than the body.
The defaults Snyk and Dependabot
> Users to Avoid

- AddTrelloComment/action.yml
If the PR description contains a quotation the GitHub Action to link the Trello card will fail. This is often the case for descriptions that contain images, for example:
```
```
This is interpolated into the step as the following, which is incorrectly escaped:
```
body = "<img src="http://domain.com/image.png">"
```
We should be able to get around this by using a percent string (meaning it will handle unescaped double and single quotations):
```
body = %(<img src="http://domain.com/image.png">)
```
> Fix bug linking Trello cards when PR description contains quotation

- CheckServicePrincipal/README.md
- CheckServicePrincipal/action.yml
A github action to check the amount of days left for a service principals keys. It will return a json array containing a list of keys that will expire within 30 days by default.  The period can be over ridden by the caller.
it is up to the calling process to handle the json results, as different workflows may need to carry out different actions.
> Check service principal

- CheckServicePrincipal/action.yml
If the Log is empty afer processing add a single Dummy entry, this prevents the matrix from collapsing in the github actions. Also only return the first value, the matrix cannot call a matrix and we only usually have one key, if we have more than one it should be seen when they fix the first, and it will start to message once the first is fixed
> Add Dummy Entry

- CheckServicePrincipal/action.yml
The Check Service Principal action uses API calls to retrieve the data it needs from Azure.  The same results can be achieved much more simply using the az cli
Tested against apply-for-qualified-teacher-status, example test run [here](https://github.com/DFE-Digital/apply-for-qualified-teacher-status/actions/runs/3290507756/jobs/5423443641).
> Refactor check service principal

- DraftReleaseByTag/action.yml
**Context**
The set-output command is being deprecated and needs updating as per the [changelog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
**Changes**
- Format using vscode extension
- Update set-output to use GITHUB_OUTPUT
- Implement multiline format for release_body output
**Testing**
- [Tag found flow](https://github.com/DFE-Digital/schools-experience/actions/runs/3516398806)
- [Tag not found flow](https://github.com/DFE-Digital/schools-experience/actions/runs/3516386093)
> Remove set-output from DraftReleaseByTag

- GenerateReleaseFromSHA/action.yml
**Context**
The set-output command is being deprecated and needs updating as per the [changelog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
**Changes**
- Format using vscode extension
- Update set-output to use GITHUB_OUTPUT
- Implement multiline format for pr_text output
**Testing**
- [Found flow](https://github.com/DFE-Digital/schools-experience/actions/runs/3522591806/jobs/5905748074)
- [Not found flow](https://github.com/DFE-Digital/schools-experience/actions/runs/3522525085/jobs/5905602648)
> Remove set-output from GenerateReleaseFromSHA

- DraftReleaseByTag/action.yml
The old DraftReleaseByTag output the release_body in a JSON format. The recent update did not include this. Updating the action to fix downstream formatting issues.
> Make release_body output JSON

- AddTrelloComment/action.yml
Context
The set-output command is being deprecated and needs updating as per the [changelog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
Changes
- Format using vscode extension
- Update the set-output usage to use ruby append file
Testing
- https://github.com/DFE-Digital/schools-experience/actions/runs/3525614567/jobs/5912548764
> 700 update set output usage add trello comment

- README.md
- set-arm-environment-variables/README.md
- set-arm-environment-variables/action.yaml
This adds a GitHub Action which sets the `ARM_` environment variables suitable for running Terraform. We have a similar action in a number of workflows now so we should move it to a common place.
> Add "Set ARM environment variables"

- build-docker-image/README.md
- build-docker-image/action.yml
The tag of the docker image is generated in the action. We now output it so it can be used in the deployment.
See https://github.com/DFE-Digital/teacher-pay-calculator/actions/runs/5424495019/jobs/9864053944
> [448] Docker image tag output

- build-docker-image/action.yml
It looks like the environment variable has to be in all capital letters for it to work.
Example failing build: https://github.com/DFE-Digital/apply-for-qualified-teacher-status/actions/runs/5424481103/jobs/9863897446?pr=1531
Example working build: https://github.com/DFE-Digital/apply-for-qualified-teacher-status/actions/runs/5424624084/jobs/9864245409?pr=1531
> Set SNYK_TOKEN environment variable

- build-docker-image/README.md
- build-docker-image/action.yml
Added optional parameter context, By setting value "." , docker/build-push-action will not pull git , it will use existing context.
Optional parameter **context** added
Without context parameter, the action will pull like this 
```
#1 [internal] load git source https://github.com/DFE-Digital/technical-guidance.git#refs/pull/188/merge
#1 0.043 Initialized empty Git repository in /var/lib/docker/overlay2/d5jvo1twwso02k0m05r5zo9g4/di
```
By adding a context parameter with value "." , you will not see  **Initialized empty Git**
> context parameter added

- build-docker-image/README.md
- build-docker-image/action.yml
Make it easier to adopt this action by removing the need to pass in the argument
Default the docker repository name to the Github repository
See it in action: https://github.com/DFE-Digital/technical-guidance/actions/runs/7105521974/job/19342894406
> Make docker repository optional in build-docker-image

- README.md
- set-kubelogin-environment/README.md
- set-kubelogin-environment/action.yaml
Simplify migration to Azure RBAC enabled clusters. This can replace the `set-arm-environment-variables` action to configure kubelogin as well.
New action which calls set-arm-environment-variables then configures kubelogin for service principal authentication
Check PR https://github.com/DFE-Digital/register-trainee-teachers/pull/3949
> [925] set-kubelogin-environment action

- set-kubelogin-environment/action.yaml
Deprecation warnings:
> Deploy Cluster (platform-test)
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: Azure/login@v1, azure/use-kubelogin@v1, azure/setup-kubectl@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
The v1.2 version has node20 but the v1 tag was not updated. [Created an issue](https://github.com/Azure/use-kubelogin/issues/50) to fix the tag, but in the meantime, upgraded to the latest version of azure/use-kubelogin
Updated action.yaml  azure/use-kubelogin version 1.2
Any Pipelines using this actions  should not show warning , Ex: teachers-services-cloud
> azure/use-kubelogin upgraded to 1.2

- build-docker-image/action.yml
The tags are normally set based on branches and git sha when using push or pull_request events. It fails for workflow_dispatch or schedule events
For other events like workflow_dispatch or schedule, branches and git sha are not relevant so we use a timestamp and main as default branch.
See successful run in Apply: https://github.com/DFE-Digital/apply-for-teacher-training/actions/runs/9100285983
> [1823] Make build-docker-image work for other event types

- set-kubectl/action.yaml
Kubectl version upgraded to 1.27.9 to align with AKS cluster version.
Kubectl version upgraded to 1.27.9 to align with AKS cluster version.
> Kubectl version updated to 1.27.9 to align with AKS

- backup-postgres/README.md
- backup-postgres/action.yml
- install-postgres-client/action.yml
- restore-postgres-backup/README.md
- restore-postgres-backup/action.yml
The action was failing for version 16, required for Claims
See: https://github.com/DFE-Digital/claim-additional-payments-for-teaching/actions/runs/9910221790/job/27380095791
- Delete conflicting default postgres client 14 before installing 16
Other improvements:
- Remove the need for existing `./bin` directory by downloading konduit.sh in the current directory
See sucessful runs:
- Backup: https://github.com/DFE-Digital/claim-additional-payments-for-teaching/actions/runs/9910221790/job/27385133608
- Restore: https://github.com/DFE-Digital/claim-additional-payments-for-teaching/actions/runs/9937920315/job/27449265757
> [1914] Fix backup-postgres and install-postgres-client for version 16

- .github/workflows/reusable-workflow-sast.yml
- sast-reusable-workflow/README.md
Added documentation for GitHub Compliance App, and logic to allow semgrep in case repo is private or developer preference.
v1 of this workflow would not have worked for private repos due to licensing issues. 
This version includes:
* checks to see if the repo is private which triggers semgrep instead of codeql
* the option to force semgrep if a team prefers it to codeql
* naming and uploading of artefacts so they can be picked up by the security teams reporting tools
* extra documentation to explain the compliance check, and how to ensure it runs in your pipeline
* the compliance job will now run so long as the repo is public, now that the app has been installed in this org and secrets are available
Successful run on test repo, shows build breaking due to security issues found outside of …
> SAST reusable workflow documentation and additional functionality

- backup-postgres/README.md
- backup-postgres/action.yml
https://trello.com/c/Zkl78tQ5/1977-backup-ptr-database-using-github-action
Update backup-postgres github action so that a PTR postgres server can be backed up
Add ptr-db-server-name to the github action, which will be invoked by konduit -s when specified as an input
backup of source server (s189d01-rtt-rv-pg)
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/10390616053
backup of PTR copy (s189d01-rtt-rv-pg-ptr)
https://github.com/DFE-Digital/register-trainee-teachers/actions/runs/10390757032 
remove 'for dev testing' commit before merge
> Allow backup of PTR server using backup-postgres

- .github/workflows/reusable-workflow-sast.yml
Update policy-as-code action and remove upload artifacts for codeql (no longer necessary for codeql).
Includes two updates:
1. Update the policy as code action to the latest version.
2. Remove upload artifact steps for codeql as we are now retrieving data for that step via the github api. Semgrep still requires an artifact due to licensing issues with github.
> Update policy-as-code action and remove upload artifacts for codeql

- .github/dependabot.yml
Dependabot was turned off for this repo, and the existing PRs were for a workflow that no longer exists. This config creates groups to ensure we can update each workflow independently, with their dependencies grouped as a single PR for each directory. There are a number of outdated workflows, so I expect there to be a few PRs raised when we merge.
dependabot.yml config to organise and turn on dependabot for github actions.
I left out the "reviewers" for this because I don't know who owns what. It might be worth us creating a CODEOWNERS file for this repo so the right people can be involved when PRs are raised against actions their team built.
We should watch out for the PRs and review/merge them when they are raised.
> Add dependabot config to keep workflows up to date

- .github/workflows/reusable-workflow-sast.yml
* Change name of semgrep artifact to use simplified vars and add semgrep to the end of the artifact name
* Remove unnecessary commands/comments.
The original commands were unnecessarily complex, we also need to have the word "semgrep" in the name to allow us to filter artifacts when the security team are gathering data and collecting sarif files.
> SAST: Change name of semgrep artifact

- backup-postgres/README.md
- backup-postgres/action.yml
Rename the argument in the backup DB workflow for clarity as it can be applied to any database server, not specifically point-in-time.
Rename argument and update description
https://github.com/DFE-Digital/teaching-record-system/actions/runs/11167470580
The argument must be updated in ITTMS and TRS workflows
> [2034] Rename ptr-db-server-name to db-server-name

- build-docker-image/README.md
- build-docker-image/action.yml
Add registry max caching option to build-docker-image 
Updates to build-docker-image workflow and readme
- add max-cache input
single stage docker image
- max cache (reuse-cache=true,max-cache=true): https://github.com/DFE-Digital/get-a-teacher-relocation-payment/actions/runs/11383642707
- break max cache: (reuse-cache=false,max-cache=true): https://github.com/DFE-Digital/get-a-teacher-relocation-payment/actions/runs/11383931620
multi stage docker image
- max cache (reuse-cache=true,max-cache=true): https://github.com/DFE-Digital/itt-mentor-services/actions/runs/11386288131
- break max cache: (reuse-cache=false,max-cache=true): https://github.com/DFE-Digital/itt-mentor-services/actions/runs/11388279565
> Add max caching option to build-docker-image

- build-docker-image/README.md
- build-docker-image/action.yml
- deploy-to-aks/README.md
- deploy-to-aks/action.yml
Create AKS deploy action
Add deploy-to-aks action and Readme.
Add slack failure notification to build action
see https://github.com/DFE-Digital/get-a-teacher-relocation-payment/actions/runs/11616882883 run from https://github.com/DFE-Digital/get-a-teacher-relocation-payment/pull/447
> create deploy-to-aks action

- build-docker-image/action.yml
build-docker-image returns an image output that contains upper case letters, causing deploy to fail
e.g. DFE-Digital instead of dfe-digital
use lower case DOCKER_REPOSITORY for the output
https://github.com/DFE-Digital/find-a-lost-trn/actions/runs/12810348606 uses this branch
> Use lower case build image name

- install-postgres-client/action.yml
install-postgres-client fails after runner update to ubuntu 24
it contains a hardcoded delete for the postgres 14 client which doesn't exist on the new version
Only delete if it exists
https://github.com/DFE-Digital/schools-experience/actions/runs/12828486968
> Fix install-postgres-client for ubuntu 24

- deploy-domains-env/README.md
- deploy-domains-env/action.yml
- deploy-domains-infra/README.md
- deploy-domains-infra/action.yml
Actions for CI-CD for domains 
actions to deploy infrastructure domains and environment domains callable from workflows
initially these actions just do terraform plan for testing.  Will be changed to apply before merge
[Implement CI/CD for domains on all services](https://trello.com/c/unElJf6I/2168-implement-ci-cd-for-domains-on-all-services)
tested by using the itt-mentor-services to run workflows to call these actions. 
see PR https://github.com/DFE-Digital/itt-mentor-services/pull/1287
> CI-CD for domains

- backup-postgres/README.md
- restore-postgres-backup/README.md
The namespace is required when the user is not cluster admin. It is the standard so it should be explicit in the documentation.
Add the namespace to the readmes
Review readmes, compare with implementation in ITTMS
> [2201] Add namespace to database action examples

- build-docker-image/README.md
- build-docker-image/action.yml
When using workflow_dispatch, the branch name was not used and there was no tag with the commit id.
Automatically read the branch name and commit id from the git context and use them as docker tags
See successful runs:
- pull_request: https://github.com/DFE-Digital/early-careers-framework/actions/runs/13053879329
- workflow_dispatch: https://github.com/DFE-Digital/early-careers-framework/actions/runs/13052085495
- schedule: https://github.com/DFE-Digital/find-a-lost-trn/actions/runs/13054046574/job/36420647948
> [2221] Use git data for all docker build tags

- set-kubectl/action.yaml
https://trello.com/c/Gb9zGC6R/2255-aks-upgrade-to-131
There is a requirement to keep up with the Kubernetes releases for bug fixes and new functionality.
Update the kubectl client version to match the aks cluster version 1.31.5.
kubectl client in github actions should use the updated version.
> Update kubectl client version to 1.31.5

- deploy-to-aks/action.yml
deploy-to-aks action incorrectly runs ci after env for terraform-apply
change
make ${{ inputs.environment }} ci terraform-apply
to
make ci ${{ inputs.environment }} terraform-apply
$make production ci terraform-plan
Makefile:22: *** Missing CONFIRM_PRODUCTION=yes.  Stop.
$make ci production terraform-plan
make: `ci' is up to date.
make: `production' is up to date.
etc
> Move ci before env in Makefile deploy

- backup-postgres/README.md
- backup-postgres/action.yml
Workflow differs to backup-postgres as it retains the schema but excludes specified tables as part of pg_dump, to support the sanitisation process on Github runners for larger databases.
This is to add a separate workflow to drop large unnecesary tables from the production database for the backups sanitisation process.
Retain schema and run pg_dump with excluded tables
https://github.com/DFE-Digital/apply-for-teacher-training/actions/runs/14474795321/job/40597683718 Succesful backup run with sanitisation from new workflow.
> Add sanitise flag backup-postgres

- backup-postgres/action.yml
Bug fix for the `backup-postgres` GitHub Action where the table exclusion feature was not working. Despite specifying tables to exclude in sanitized backup workflows, all data was still being included, creating larger backups and potentially exposing sensitive data.
Fixed the table exclusion mechanism by:
- Improved bash array handling to properly process the exclude-tables input parameter
- Added support for both comma and space-separated table lists
- Ensured proper construction of pg_dump exclude options
- Run the `backup-db-sanitise.yml` workflow manually in a test environment
- Verify that specified tables have their structure preserved but data excluded
- Check that the backup file size is smaller than previous backups
- https://github.com/DFE-Digital/apply-for-teacher-training/actio …
> Fix table exclusion in backup GitHub Action

- backup-postgres/action.yml
Enable overwrite protection for existing postgres backups in azure storage
Enable overwrite protection for existing postgres backups in azure storage
overwrite flag -- overwrite is not a valid option.
https://learn.microsoft.com/en-us/cli/azure/storage/azcopy/blob?view=azure-cli-latest#az-storage-azcopy-blob-upload
Backups taken after verifying the backup does not exist on the given backup name
https://github.com/DFE-Digital/find-a-lost-trn/actions/runs/15872296239
Backups protected. No backup taken and uploaded to azure storage. job failed.
https://github.com/DFE-Digital/find-a-lost-trn/actions/runs/15872626293
> Enable overwrite protection for existing postgres backups in azure storage

- build-docker-image/action.yml
Snyk scanning is failing which appear to be to a recent snyk cli release 
Use the snyk cli so we can use the previous version
https://github.com/DFE-Digital/npq-registration/actions/runs/16320658817
> Temporarily use the snyk cli instead of the action

- build-docker-image/README.md
minor lint error in the build-docker-image readme
fix the error
see https://github.com/DFE-Digital/github-actions/actions/runs/16627550823/job/47048091366 for the reported error
> Fix lint error in build-docker-image readme
